# Generated by Django 5.1.5 on 2025-08-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_shipment_destination_country_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='current_location',
            field=models.CharField(default='Processing', max_length=100),
        ),
    ]
