# Generated by Django 5.1.5 on 2025-08-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_alter_shipment_current_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='mobile',
            field=models.IntegerField(default=8, max_length=15),
            preserve_default=False,
        ),
    ]
